apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}    
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}    
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
