apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "python-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "python-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
