apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app.kubernetes.io/name: python-app    
spec:
  selector:
    app.kubernetes.io/name: pythpn-app    
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
